# docker-compose の世界へレッツゴー！
services:
  app:
    
    build: .
    ports:
      - "3000:3000"
    volumes:
      # ローカルのコードをコンテナに同期！これは必須だよ！
      - .:/app 
      - /app/node_modules
      - app-cache:/app/.next/cache
      
    # ⭐️ 魔法の環境変数を追加！これがポーリングを有効にするよ！
    environment:
      # Next.js のポーリング（ファイル監視）を強制的に有効にするよ！
      - CHOKIDAR_USEPOLLING=true
      # または、Next.js の watchpack のポーリングを有効にするよ！
      - WATCHPACK_POLLING=true
      
    # 開発サーバーを起動！
    command: npm run dev
volumes:
  app-cache: